modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="demonmod"
version="Alpha V.3"
displayName="Demon Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="isuta, MCreator"

[[dependencies.demonmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



